source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPWelcomeVC_Example' do
  pod 'POPWelcomeVC', :path => '../'

  target 'POPWelcomeVC_Tests' do
    inherit! :search_paths
  end

end


